services:
  db:
    image: postgres:18-alpine
    container_name: autosales_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 4s
    networks:
      - default_network

  redis:
    image: redis:8-alpine
    container_name: autosales_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default_network

  backend:
    build:
      context: ./backend_rust
      dockerfile: Dockerfile
    container_name: autosales_backend_rs

    environment:
      BACKEND_PORT: 8000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_NAME}
      CORS_ORIGINS: ${CORS_ORIGINS}

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - default_network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:${BACKEND_PORT}/api/admin
        NEXT_PUBLIC_IMAGES_URL: http://backend:${BACKEND_PORT}/api/images
    container_name: autosales_frontend

    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default_network

  bot:
    build:
      context: ./tgbot_rust
      dockerfile: Dockerfile
    container_name: autosales_bot

    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      API_URL: http://backend:${BACKEND_PORT}/api
      SUPPORT_URL: ${SUPPORT_URL}
      PAYMENT_INSTRUCTIONS_URL: ${PAYMENT_INSTRUCTIONS_URL}
      SERVICE_TOKEN: ${SERVICE_API_KEY}

    depends_on:
      - backend

    networks:
      - default_network

  mock_gateway:
    build:
      context: ./mock_payment_gateway
      dockerfile: Dockerfile
    container_name: autosales_mock_gateway
    environment:
      MAIN_BACKEND_WEBHOOK_URL: http://localhost:8000/api/webhook/payment/mock-provider
      MOCK_GATEWAY_PUBLIC_URL: ${MOCK_GATEWAY_PUBLIC_URL}
    ports:
      - "8078:8078"
    networks:
      - default_network

volumes:
  db-data:

networks:
  default_network:
    driver: bridge
